drop table if exists product_review_vote cascade;
drop table if exists seller_review_vote cascade;
drop table if exists cartitem cascade;
drop table if exists cart cascade;
drop table if exists inventory cascade;
drop table if exists product_review cascade;
drop table if exists seller_review cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists balance_tx cascade;
drop table if exists account_balance cascade;
drop table if exists purchases cascade;
drop table if exists wishes cascade;
drop table if exists products cascade;
drop table if exists users cascade;

create table users (
    id int not null primary key generated by default as identity,
    email text unique not null,
    full_name text not null,
    address text not null,
    password_hash text not null,
    created_at timestamptz not null default now(),
    cart integer[],
    purchases integer[]
);

create table account_balance (
    user_id int primary key references users(id) on delete cascade,
    balance_cents bigint not null default 0
);

create table balance_tx (
    id int not null primary key generated by default as identity,
    user_id int not null references users(id) on delete cascade,
    amount_cents bigint not null,
    created_at timestamptz not null default now(),
    note text
);

create table products (
    id int not null primary key generated by default as identity,
    name text unique not null,
    price decimal(12,2) not null,
    available boolean default true,
    image_url text,
    description text
);


create table orders (
    id int not null primary key generated by default as identity,
    buyer_id int references users(id) on delete set null,
    created_at timestamptz not null default now(),
    total_cents bigint not null,
    fulfilled boolean not null default false
);

create table order_items (
    id int not null primary key generated by default as identity,
    order_id int not null references orders(id) on delete cascade,
    product_id int not null references products(id),
    seller_id int,
    quantity int not null check (quantity > 0),
    unit_price_cents bigint not null check (unit_price_cents >= 0),
    fulfilled_at timestamptz
);

create table purchases (
    id int not null primary key generated by default as identity,
    uid int not null references users(id) on delete cascade,
    pid int not null references products(id),
    time_purchased timestamptz not null default (current_timestamp at time zone 'utc')
);

create table wishes (
    id int not null primary key generated by default as identity,
    uid int not null references users(id) on delete cascade,
    pid int not null references products(id),
    time_added timestamptz not null default (current_timestamp at time zone 'utc')
);

create table inventory (
    user_id int not null references users(id) on delete cascade,
    product_id int not null references products(id) on delete cascade,
    quantity int not null check (quantity >= 0),
    primary key (user_id, product_id)
);

create table seller_review (
    id int not null primary key generated by default as identity,
    user_id int not null references users(id) on delete cascade,
    seller_id int not null references users(id) on delete cascade,
    rating int not null check (rating >= 1 and rating <= 5),
    body text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint unique_user_seller unique (user_id, seller_id)
);

create table product_review (
    id int not null primary key generated by default as identity,
    user_id int not null references users(id) on delete cascade,
    product_id int not null references products(id) on delete cascade,
    rating int not null check (rating >= 1 and rating <= 5),
    body text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint unique_user_product unique (user_id, product_id)
);

CREATE TABLE cart (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cartitem (
    id SERIAL PRIMARY KEY,
    cart_id INT NOT NULL REFERENCES cart(id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(id),
    quantity INT NOT NULL CHECK (quantity > 0)
);

-- votes for product reviews (one per user per review, value 1=upvote, -1=downvote)
create table product_review_vote (
    user_id int not null references users(id) on delete cascade,
    review_id int not null references product_review(id) on delete cascade,
    vote_value int not null check (vote_value in (-1, 1)),
    created_at timestamptz not null default now(),
    primary key (user_id, review_id)
);

-- votes for seller reviews (one per user per review, value 1=upvote, -1=downvote)
create table seller_review_vote (
    user_id int not null references users(id) on delete cascade,
    review_id int not null references seller_review(id) on delete cascade,
    vote_value int not null check (vote_value in (-1, 1)),
    created_at timestamptz not null default now(),
    primary key (user_id, review_id)
);

-- Indexes to keep purchase lookups fast under pagination/filtering
CREATE INDEX IF NOT EXISTS idx_orders_buyer_created ON orders (buyer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_seller_id ON order_items (seller_id);
CREATE INDEX IF NOT EXISTS idx_products_name_lower ON products (LOWER(name));
CREATE INDEX IF NOT EXISTS idx_product_review_vote_review ON product_review_vote (review_id);
CREATE INDEX IF NOT EXISTS idx_seller_review_vote_review ON seller_review_vote (review_id);
CREATE INDEX IF NOT EXISTS idx_reviews_productid ON product_reviews (product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_productid_date ON product_reviews (product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_productid_rating ON product_reviews (product_id, rating);
